image: registry.gitlab.eox.at/maps/docker-base/snap-mapchete:latest

before_script:
  - pip install cython numpy
  - pip install -e .[mundi,test]

test:
  script:
    - pytest -v --cov=mapchete_hub tests/
