image: registry.gitlab.eox.at/maps/docker-base/mapchete:latest

before_script:
  - pip install Cython
  - pip install git+http://gitlab+deploy-token-4:9wY1xu44PggPQKZLmNxj@gitlab.eox.at/maps/orgonite.git git+http://gitlab+deploy-token-3:SV2HivQ_xiKVxSVEtYCr@gitlab.eox.at/maps/mapchete_satellite.git
  - pip install -r requirements.txt -r requirements_test.txt
  - python setup.py develop

test:
  script:
    - pytest -v --cov=mapchete_hub tests/
