default:
  before_script:
    - apt-get update && apt-get install --yes --no-install-recommends gcc git
    - pip install cython numpy
    - pip install -e .[mundi,test]

test_base_image:0.4:
  image: registry.gitlab.eox.at/maps/docker-base/snap-mapchete:0.4
  script:
    - pytest -v --cov=mapchete_hub tests/

test_base_image:0.5:
  image: registry.gitlab.eox.at/maps/docker-base/snap-mapchete:0.5
  script:
    - pytest -v --cov=mapchete_hub tests/

test_base_image:latest:
  image: registry.gitlab.eox.at/maps/docker-base/snap-mapchete:latest
  script:
    - pytest -v --cov=mapchete_hub tests/
