repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.6.8
  hooks:
    # Run the linter.
    - id: ruff
      args: [ --fix ]
    # Run the formatter.
    - id: ruff-format
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.11.2
  hooks:
    - id: mypy
      verbose: true
      args: [--show-error-codes, --ignore-missing-imports, --disable-error-code=import-untyped]
      additional_dependencies: ["types-python-dateutil", "types-retry", "types-croniter"]
- repo: local
  hooks:
  - id: rst
    name: rst
    entry: rst-lint --encoding utf-8
    files: ^(CHANGELOG.rst|README.rst)$
    language: python
    additional_dependencies: [pygments, restructuredtext_lint]