version: "3.8"

services:

  mhub_tester:
    build:
      context: .
    environment:
      - MHUB_HOST=http://server:${MHUB_PORT:-5000}
    command: |
      /bin/bash -c "
        echo $MHUB_HOST;
        sleep 5;
        uv pip install --extra test -r /usr/local/src/mapchete_hub/pyproject.toml && python -m pytest -v --cov=mapchete_hub /usr/local/src/mapchete_hub/tests/test_app_integration.py && coverage report
      "
    networks:
      - backend

networks:
  backend:
