version: "3.6"

services:

  db:
    image: mongo:4.2.7-bionic
    networks:
      - backend
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mhub
      - MONGO_INITDB_ROOT_PASSWORD=REDACTED_API_KEY
      # https://github.com/docker-library/mongo/issues/329
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    volumes:
      - db-data:/data/db
    command: [ "--bind_ip_all" ]

  server:
    image: "registry.gitlab.eox.at/maps/mapchete_hub/${IMAGE_NAME:-mhub}:${IMAGE_TAG}"
    depends_on:
      - db
      - dask_scheduler
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REQUEST_PAYER=${AWS_REQUEST_PAYER}
      - MHUB_DASK_SCHEDULER_URL=tcp://dask_scheduler:8786
      - MHUB_MONGODB_URL=mongodb://mhub:REDACTED_API_KEY@db:27017
      - MHUB_ADD_MAPCHETE_LOGGER=true
      - MHUB_PORT=${MHUB_PORT:-5000}
    networks:
      - backend
    ports:
      - ${MHUB_PORT:-5000}:${MHUB_PORT:-5000}
    command:
      [
        "mhub-server",
        "start",
        "--host",
        "0.0.0.0",
        "--port",
        "${MHUB_PORT:-5000}",
        "--log-level",
        "debug"
      ]

  dask_scheduler:
    image: "registry.gitlab.eox.at/maps/mapchete_hub/${IMAGE_NAME:-mhub}:${IMAGE_TAG}"
    networks:
      - backend
    command:
      [
        "dask-scheduler",
        "--host",
        "dask_scheduler",
        "--port",
        "8786"
      ]

  dask_worker:
    image: "registry.gitlab.eox.at/maps/mapchete_hub/${IMAGE_NAME:-mhub}:${IMAGE_TAG}"
    depends_on:
      - dask_scheduler
    networks:
      - backend
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REQUEST_PAYER=${AWS_REQUEST_PAYER}
      - DASK_LOGGING__MAPCHETE="debug"
    command:
      [
        "dask-worker",
        "--nthreads",
        "2",
        "--nprocs",
        "8",
        "tcp://dask_scheduler:8786"
      ]

volumes:
  db-data:

    null
networks:
  backend: null
