version: "3.6"

services:

  mhub_tester:
    image: "registry.gitlab.eox.at/maps/mapchete_hub/${IMAGE_NAME:-mhub}:${IMAGE_TAG:-latest}"
    environment:
      - MHUB_HOST=http://server:${MHUB_PORT:-5000}
    command: /bin/bash -c "echo $MHUB_HOST; sleep 5; pip install -r requirements_test.txt && python -m pytest -v --cov=mapchete_hub && coverage report"
    networks:
      - backend

networks:
  backend:
