version: "3.6"

services:

  db:
    image: mongo:4.2.7-bionic
    networks:
      - backend
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mhub
      - MONGO_INITDB_ROOT_PASSWORD=REDACTED_API_KEY
      # https://github.com/docker-library/mongo/issues/329
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    volumes:
      - db-data:/data/db
    command: ["--bind_ip_all"]

  server:
    build: .
    depends_on:
      - redis
      - dask_scheduler
      - db
    environment:
      - REDIS_URL=redis://redis:6379
      - DASK_SCHEDULER=tcp://dask_scheduler:8786
      - MHUB_STATUS_DB_URI=mongodb://mhub:REDACTED_API_KEY@db:27017
    networks:
      - backend
    ports:
      - 5000:8000
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--log-level", "debug"]

  redis:
    image: redis:6.2.5-alpine
    networks:
      - backend

  dask_scheduler:
    build: .
    networks:
      - backend
    ports:
      - "8786:8786"
    command: ["dask-scheduler", "--host", "dask_scheduler", "--port", "8786"]

  dask_worker:
    build: .
    depends_on:
      - dask_scheduler
    networks:
      - backend
    command: ["dask-worker", "--nthreads", "1", "--nprocs", "8", "tcp://dask_scheduler:8786"]

volumes:
  db-data:

networks:
  backend:
