version: "3.6"

services:

  broker:
    image: mongo:4.2.7-bionic
    networks:
      - backend
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mhub
      - MONGO_INITDB_ROOT_PASSWORD=REDACTED_API_KEY
      # https://github.com/docker-library/mongo/issues/329
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    command: ["--bind_ip_all"]

  db:
    image: mongo:4.2.7-bionic
    networks:
      - backend
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mhub
      - MONGO_INITDB_ROOT_PASSWORD=REDACTED_API_KEY
      # https://github.com/docker-library/mongo/issues/329
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    volumes:
      - db-data:/data/db
    command: ["--bind_ip_all"]

  monitor:
    build:
      context: .
      args:
        BASE_IMAGE_NAME: "${BASE_IMAGE_NAME:-mapchete}"
    command: ./manage.py monitor --loglevel=DEBUG
    networks:
      - backend
    depends_on:
      - broker
      - db
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
    environment:
      - MONGODB_PORT
      - CURL_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt
      - MHUB_BROKER_URI=mongodb://mhub:REDACTED_API_KEY@broker:27017
      - MHUB_CONFIG_DIR=/mnt/data/
      - MHUB_ENV=debug
      - MHUB_RESULT_BACKEND_URI=mongodb://mhub:REDACTED_API_KEY@broker:27017
      - MHUB_STATUS_DB_URI=mongodb://mhub:REDACTED_API_KEY@db:27017

  server:
    build:
      context: .
      args:
        BASE_IMAGE_NAME: "${BASE_IMAGE_NAME:-mapchete}"
    command: gunicorn --bind 0.0.0.0:${MHUB_PORT:-5000} --log-level DEBUG --workers 4 --threads 4 --worker-class=gthread --worker-tmp-dir /dev/shm "mapchete_hub.flask_app:flask_app()"
    networks:
      - backend
    depends_on:
      - broker
      - db
      - monitor
    ports:
      - ${MHUB_PORT:-5000}:${MHUB_PORT:-5000}
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
    environment:
      - CURL_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt
      - MHUB_BROKER_URI=mongodb://mhub:REDACTED_API_KEY@broker:27017
      - MHUB_CONFIG_DIR=/mnt/data/
      - MHUB_ENV=debug
      - MHUB_RESULT_BACKEND_URI=mongodb://mhub:REDACTED_API_KEY@broker:27017
      - MHUB_STATUS_DB_URI=mongodb://mhub:REDACTED_API_KEY@db:27017

  execute_worker:
    build:
      context: .
      args:
        BASE_IMAGE_NAME: "${BASE_IMAGE_NAME:-mapchete}"
    command: ./manage.py worker -n execute_worker -q overview_queue,execute_queue --loglevel=DEBUG
    networks:
      - backend
    depends_on:
      - broker
      - server
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
    environment:
      - CURL_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt
      - MHUB_BROKER_URI=mongodb://mhub:REDACTED_API_KEY@broker:27017
      - MHUB_CONFIG_DIR=/mnt/data
      - MHUB_ENV=debug
      - MHUB_RESULT_BACKEND_URI=mongodb://mhub:REDACTED_API_KEY@broker:27017
      - MP_SATELLITE_CACHE_PATH=/mnt/data/cache

  index_worker:
    build:
      context: .
      args:
        BASE_IMAGE_NAME: "${BASE_IMAGE_NAME:-mapchete}"
    command: ./manage.py worker -n index_worker -q index_queue --loglevel=DEBUG
    networks:
      - backend
    depends_on:
      - broker
      - server
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
    environment:
      - CURL_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt
      - MHUB_BROKER_URI=mongodb://mhub:REDACTED_API_KEY@broker:27017
      - MHUB_CONFIG_DIR=/mnt/data
      - MHUB_ENV=debug
      - MHUB_INDEX_OUTPUT_DIR=/mnt/data/indexes
      - MHUB_RESULT_BACKEND_URI=mongodb://mhub:REDACTED_API_KEY@broker:27017
      - MP_SATELLITE_CACHE_PATH=/mnt/data/cache

volumes:
  db-data:

networks:
  backend:
