version: "3.6"

services:

  rabbitmq:
    image: rabbitmq:3
    ports:
      - 5672
    networks:
      - backend
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
    environment:
      - RABBITMQ_DEFAULT_USER=s2processor
      - RABBITMQ_DEFAULT_PASS=REDACTED_API_KEY

  server:
    image: registry.gitlab.eox.at/maps/mapchete_hub/server:0.2
    networks:
      - backend
    depends_on:
      - rabbitmq
      - monitor
    ports:
      - 5000:5000
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
    env_file: server.env
    environment:
      - SUBCOMMAND=devserver
      - MHUB_BROKER_URL=amqp://s2processor:REDACTED_API_KEY@rabbitmq:5672//
      - MHUB_RESULT_BACKEND=rpc://s2processor:REDACTED_API_KEY@rabbitmq:5672//
    volumes:
      - type: volume
        source: status_data
        target: /mnt/data/

  zone_worker:
    image: registry.gitlab.eox.at/maps/mapchete_hub/worker:0.2
    networks:
      - backend
    depends_on:
      - rabbitmq
      - server
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
    env_file: zone_worker.env
    environment:
      - MHUB_BROKER_URL=amqp://s2processor:REDACTED_API_KEY@rabbitmq:5672//
      - MHUB_RESULT_BACKEND=rpc://s2processor:REDACTED_API_KEY@rabbitmq:5672//
    volumes:
      - type: volume
        source: worker_data
        target: /mnt/data/

networks:
  backend:

volumes:
  status_data:
  worker_data:
