# .github/workflows/pr-check.yml
name: PR Check - Build Docker Image

on:
  pull_request:
    branches:
      - 'main'

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image for validation
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: .
          # Build the image but DO NOT push it
          push: false
          # Load the image into the local Docker daemon so it can be used by later steps for testing
          load: true
          tags: pr-check-${{ github.event.number }}

      # You can add additional steps here to test the built image
      - name: Run tests on the container
        run: docker run --rm pr-check-${{ github.event.number }} mhub-server --help
